### ISSUE TITLE
bad visualization of "not done or uncompleted" sessions on week report

### ISSUE THREAD

**Issue by pereschristophe** [La0/coach#139]
![image](https://cloud.githubusercontent.com/assets/10983929/6328542/e1818ff8-bb68-11e4-8b46-41c50d50aa46.png)

when exporting week, "not done or uncompleted" sessions are not clearly indicated - of course you can have a look at the bottom of the export bit it is not obvious
I could add that a "modified" option can be added to possibilities when athlete enters its job (à faire, fait, manqué)

**Comment by La0** [comment]
Same issue in week view.
