### ISSUE TITLE
RunReport can't import Multisport activities from the new Garmin Connect

### ISSUE THREAD

**Issue by bioub** [La0/coach#165]
Since a few months, Garmin Connect group multi-activities like Triathlon. They are not imported to Run Report.

![capture d ecran 2015-05-25 a 14 04 30](https://cloud.githubusercontent.com/assets/1698236/7801839/2cf2571a-032b-11e5-9859-3e0a518daa0b.png)

**Comment by La0** [comment]
Fixed : https://runreport.fr/user/romain_bohdanowicz/day/2015/5/24 :runner:
